name: marl
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11.0
  - pip
  - pip:
    - cloudpickle==3.0.0
    - colorama==0.4.6
    - contourpy==1.3.0
    - cycler==0.12.1
    - farama-notifications==0.0.4
    - filelock==3.16.1
    - fonttools==4.54.1
    - fsspec==2024.9.0
    - gymnasium==0.29.1
    - jinja2==3.1.4
    - kiwisolver==1.4.7
    - markupsafe==3.0.1
    - matplotlib==3.9.2
    - mpmath==1.3.0
    - networkx==3.4.1
    - numpy==1.26.4
    - packaging==24.1
    - pandas==2.2.3
    - pettingzoo==1.24.3
    - pillow==10.4.0
    - pyparsing==3.2.0
    - python-dateutil==2.9.0.post0
    - pytz==2024.2
    - sb3-contrib==2.3.0
    - six==1.16.0
    - stable-baselines3==2.3.2
    - sympy==1.13.3
    - torch==2.2.2
    - typing-extensions==4.12.2
    - tzdata==2024.2